name: CI when have new code merge to main

on:
  push:
    branches: [ "main" ]

jobs:
  pull-code-build-image-run-containers:
    runs-on: ubuntu-latest
    environment: cd

    steps:
    - name: SSH and build
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /home/hanzirush
          rm -r ./HanziRushBE
          git clone ${{ secrets.PROJ_URL }}
          cd ./HanziRushBE

          docker build -t ${{ vars.APP_NAME }}:${{ github.sha }} -f ./Docker/Dockerfile .

          docker tag ${{ vars.APP_NAME }}:${{ github.sha }} ${{ vars.APP_NAME }}:latest

          docker run -p 80:8000 ${{ vars.APP_NAME }}:${{ github.sha }} ${{ vars.APP_NAME }}:latest